baseURL = 'https://mollysec.com/'
languageCode = 'en-gb'
title = 'mollysec'
theme = 'PaperMod'

[params]
  description = 'Security research and technical writeups'
  introDescription = 'Welcome to mollysec'
  logo = 'images/mollysec-logo-32x32.png'
  footerLogo = 'images/mollysec-logo-32x32.png'
  twitterCard = 'summary_large_image'  # For Twitter previews
  openGraph = true
  favicon = 'images/mollysec-logo-32x32.png'
  author = 'mollysec'
  math = true

[params.social]
    email = 'spaniascharalampos@gmail.com'
    github = 'https://github.com/CSpanias'
    linkedin = 'https://www.linkedin.com/in/charalamposspanias/'

[markup.goldmark.renderer]
  unsafe = true

[markup.goldmark.extensions.passthrough]
  enable = true
  [markup.goldmark.extensions.passthrough.delimiters]
    block = [
      ["\\[", "\\]"],
      ["$$", "$$"]
    ]
    inline = [
      ["\\(", "\\)"],
      ["$", "$"]
    ]
  
[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = 'Posts'
    url = '/posts/'
    weight = 2
  [[menu.main]]
    name = 'About'
    url = '/about'
    weight = 3