baseURL = 'https://mollysec.com/'
languageCode = 'en-us'
title = 'MollySec'
theme = 'clarity'

[params]
  description = 'Security research and technical writeups'
  introDescription = 'Welcome to MollySec'
  logo = '/images/mollysec-logo-32x32.png'
  footerLogo = '/images/mollysec-logo-32x32.png'
  twitterCard = 'summary_large_image'  # For Twitter previews
  openGraph = true
  favicon = '/icons/favicon.ico'
  
[params.author]
  name = 'Your Name'
  email = 'your.email@example.com'

[params.social]
    github = ''
    linkedin = ''
  
[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = 'Posts'
    url = '/posts/'
    weight = 2
  [[menu.main]]
    name = 'About'
    url = '/about/'
    weight = 3
  [[menu.main]]
    name = 'Contact'
    url = '/contact/'
    weight = 4